version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://keycloak-mysql:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    networks:
      - keycloak-journey

  keycloak-mysql:
    image: mysql:8.1.0
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: root
    networks:
      - keycloak-journey
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 3

networks:
  keycloak-journey:
    name: network-journey
    external: true